Fix choise translation
for  stopByNumberPage* keys with 'Elegir' translation keep 'choise' on src/main/resources/org/onebusaway/webapp/gwt/where_library/WhereMessages_es.properties

this cause ERROR [CommonsLogger.java:38] : Exception occurred during processing request: java.lang.IllegalArgumentException: unknown format type: Elegir
org.apache.jasper.JasperException: java.lang.IllegalArgumentException: unknown format type: Elegir